chore: Remove neptune-client dependency
neptune-ai/neptune-fetcher pull request #102
Opened 2024-10-30 10:55 UTC by PatrykGala

2024-10-30 16:13 UTC, kgodlewski requested changes

2024-10-30 16:13 UTC, kgodlewski commented on src/neptune_fetcher/read_only_project.py
> +            logger.error("Error", exc_info=True)  # TODO error handling
IMO this TODO needs to be resolved before merging

2024-10-30 16:13 UTC, kgodlewski commented on src/neptune_fetcher/read_only_project.py
> +def _extract_value(attr: ProtoAttributeDTO) -> Any:
Use `FieldType` here?

2024-10-30 16:13 UTC, kgodlewski commented on src/neptune_fetcher/read_only_project.py
> +    if sort_by == "sys/id":
It'd be good to refactor this piece of magic to a function

2024-10-30 16:13 UTC, kgodlewski commented on src/neptune_fetcher/read_only_project.py
> +                    "sorting": {
Maybe unpack `sort_by` into 3 variables, for readabilty?

2024-10-30 16:13 UTC, kgodlewski commented on src/neptune_fetcher/read_only_project.py
> +                runs.append(
How do we know that all the 3 columns below are present in the result? If not specifically requested, they won't be there, right?

2024-10-30 16:13 UTC, kgodlewski commented on src/neptune_fetcher/read_only_run.py
> +            run = read_only_project.fetch_runs_df(
`custom_id` should be escaped in all NQL queries here (after merging with `main`)

2024-10-30 16:13 UTC, kgodlewski commented on tests/prepare_runs.py
>  from neptune_scale import Run
You can delete this file, it was used only by `behave` based tests. Also, `behave` can be removed from dev dependencies

2024-11-05 10:46 UTC, PatrykGala commented on src/neptune_fetcher/fields.py
> +    STRING_SET = "stringSet"
correct

2024-11-05 10:47 UTC, PatrykGala commented on src/neptune_fetcher/nql.py
> +    NOT_MATCHES = "NOT MATCHES"
Later

2024-11-05 10:54 UTC, PatrykGala commented on src/neptune_fetcher/nql.py
> +def prepare_nql_query(
done

2024-11-05 10:55 UTC, PatrykGala commented on src/neptune_fetcher/read_only_project.py
> +            name = os.getenv(PROJECT_ENV_NAME)
exception, added

2024-11-05 10:56 UTC, PatrykGala commented on src/neptune_fetcher/read_only_project.py
> +                        executor.submit(self._fetch_columns_batch, run_ids, columns=columns, columns_regex=None)
I can't, It throws exception,

2024-11-05 10:57 UTC, PatrykGala commented on src/neptune_fetcher/read_only_project.py
> +                    if attr.type != "experimentState":
added comment

2024-11-06 10:19 UTC, kgodlewski commented on src/neptune_fetcher/fields.py
> +    STRING_SET = "stringSet"
I meant to say "not supported", but I also meant StringSeries, so the final outcome is ok 😏

2024-11-06 10:21 UTC, PatrykGala commented on src/neptune_fetcher/read_only_project.py
> +            logger.error("Error", exc_info=True)  # TODO error handling
moved to api client

2024-11-07 08:14 UTC, kgodlewski requested changes
High level points:

* It's not clear to me whether we're actually loading all the pages in all (or most) of the backend calls
* e2e tests should be green
* integration tests shouldn't be deleted. We can skip those that are too heavy to fix right now, but apart from that I don't see the reason to remove them completely.
* once we're good with the changes, the PR should be rebased to clean up commit history

2024-11-07 08:14 UTC, kgodlewski commented on src/neptune_fetcher/api/proto/__init__.py
Empty module, is it necessary?

2024-11-07 08:14 UTC, kgodlewski commented on src/neptune_fetcher/cache.py
> +    elif attr.type == "floatSeries":
We could have this as a first condition, since floatSeries would probably be most common. Yeah, heavy optimization ;)

2024-11-07 12:22 UTC, PatrykGala commented on src/neptune_fetcher/api/api_client.py
> +        resp = backoff_retry(
Pagination: https://github.com/neptune-ai/neptune-fetcher/blob/443243d2b211e93b89b2e99f5663e7390d873ea5/src/neptune_fetcher/read_only_project.py#L913

2024-11-07 12:23 UTC, PatrykGala commented on src/neptune_fetcher/api/api_client.py
> +                "attributeNameFilter": {"mustMatchRegexes": [f"^{re.escape(attribute_name)}$"]},
I want to escape regex characters from metric name, we don't have a api for query attribute definitions by name.

2024-11-07 12:24 UTC, PatrykGala commented on src/neptune_fetcher/api/api_client.py
> +                "nextPage": {"limit": 1000},
No, We want to fetch attribute definitions in project for provided name.

2024-11-07 12:39 UTC, PatrykGala commented on src/neptune_fetcher/api/api_client.py
> +            credentials=credentials, config=config, token_refreshing_urls=token_urls, proxies=proxies
later 🙏

2024-11-08 09:29 UTC, kgodlewski approved these changes

2024-11-08 10:04 UTC, kgodlewski approved these changes

2024-11-08 10:06 UTC, merged