`ReadOnlyProject` functions that fetch `DataFrame` are now concurrent.
neptune-ai/neptune-fetcher pull request #68
Opened 2024-09-25 13:58 UTC by kgodlewski

Make functions in `ReadOnlyProject` that return `pandas.DataFrame` fetch data concurrently.
This speeds up data download by 20-70 percent, depending on the data layout.

2024-09-27 06:58 UTC, PatrykGala commented on src/neptune_fetcher/read_only_project.py
> +        step_size=FETCH_RUNS_BATCH_SIZE,
`step_size=FETCH_RUNS_BATCH_SIZE,`?

2024-09-27 06:58 UTC, PatrykGala commented on src/neptune_fetcher/read_only_project.py
> +        with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
Please check the number of connections in http client.

2024-09-27 06:59 UTC, PatrykGala commented on src/neptune_fetcher/read_only_project.py
> +        with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
In near future we will use asyncio

2024-09-27 06:59 UTC, PatrykGala requested changes
LGTM

2024-09-27 09:21 UTC, kgodlewski commented on src/neptune_fetcher/read_only_project.py
> +        step_size=FETCH_RUNS_BATCH_SIZE,
It was supposed to be this way, as `step_size` controls the page size retrieved from the backend. For some reason it was hardcoded.

2024-10-02 12:21 UTC, michalsosn approved these changes

2024-10-03 11:54 UTC, PatrykGala approved these changes

2024-10-03 11:54 UTC, merged