Add tests for `ReadOnlyRun`
neptune-ai/neptune-fetcher pull request #82
Opened 2024-10-17 16:01 UTC by kgodlewski

This is an initial batch of tests that don't rely on prepopulated data, but instead log them during test execution.

In order not to interfere with existing tests that do rely on runs in a project having a specific shape, it is possible to point selected test modules to another existing project. This is already configured in GitHub Actions variables and secrets.

2024-10-22 13:50 UTC, michalsosn commented on tests/README.md
> +that already exists.
so, NEPTUNE_PROJECT - tests on prepopulated with data, NEPTUNE_E2E_PROJECT - tests on a specific data shape 
or is the opposite? I don't think it's unambiguous in this description, nor is it clear from the variable names

2024-10-22 13:57 UTC, michalsosn commented on tests/e2e/conftest.py
> +        return wrapped
```
class SyncRun(Run):
    def log(self, *args, **kwargs):
        result = super().log(*args, **kwargs)
        self.wait_for_processing()
        return result
```
hmm, would this code achieve the same thing and be somewhat simpler?

2024-10-22 14:31 UTC, kgodlewski commented on tests/e2e/conftest.py
> +        return wrapped
You're absolutely right! It requires some modification to the tests, but I'll go with it. I started with the wrapper approach for other methods as well, and ended up only needing log*(), so your solution does the thing and is indeed simpler.

2024-10-22 16:13 UTC, kgodlewski commented on tests/README.md
> +that already exists.
I changed both the descriptions and variable names for clarity

2024-10-25 10:20 UTC, michalsosn approved these changes

2024-10-25 10:57 UTC, PatrykGala requested changes
rebase to main

2024-10-25 10:58 UTC, PatrykGala approved these changes

2024-10-25 10:58 UTC, PatrykGala approved these changes

2024-10-25 11:22 UTC, merged